name: TheWalls
version: '${project.version}'
main: ca.thewalls.TheWalls
api-version: 1.21
authors: [ CKAY9 ]
description: Play The Walls in any Minecraft world
softdepend: [HologramLib, PacketEvents]
commands:
  walls:
    description: The Walls main command
    aliases: [w]
    usage: /walls <start|end|forceteam|leaderboard|events|reload|list|join|leave|team|lobby|sign|arena>
permissions:
  thewalls.start:
    default: op
  thewalls.end:
    default: op
  thewalls.forceteam:
    default: op
  thewalls.reload:
    default: op
  thewalls.leaderboard:
    default: true
  thewalls.events:
    default: true
  thewalls.walls.list:
    default: true
  thewalls.walls.join:
    default: true
  thewalls.walls.leave:
    default: true
  thewalls.walls.team:
    default: true
  thewalls.walls.lobby:
    default: op
  thewalls.walls.sign:
    default: op
  thewalls.walls:
    default: true
  thewalls.walls.arena:
    default: op
